/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppTeachersRouteImport } from './routes/_app/teachers'
import { Route as AppSovereigntyRouteImport } from './routes/_app/sovereignty'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppQuestionBankRouteImport } from './routes/_app/question-bank'
import { Route as AppOfflineRouteImport } from './routes/_app/offline'
import { Route as AppExamRouteImport } from './routes/_app/exam'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppTeachersAdminRouteImport } from './routes/_app/teachers.admin'
import { Route as AppMockWaecRouteImport } from './routes/_app/mock.waec'
import { Route as AppMockJambRouteImport } from './routes/_app/mock.jamb'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSovereigntyRoute = AppSovereigntyRouteImport.update({
  id: '/sovereignty',
  path: '/sovereignty',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionBankRoute = AppQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AppRoute,
} as any)
const AppOfflineRoute = AppOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AppRoute,
} as any)
const AppExamRoute = AppExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersAdminRoute = AppTeachersAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppTeachersRoute,
} as any)
const AppMockWaecRoute = AppMockWaecRouteImport.update({
  id: '/mock/waec',
  path: '/mock/waec',
  getParentRoute: () => AppRoute,
} as any)
const AppMockJambRoute = AppMockJambRouteImport.update({
  id: '/mock/jamb',
  path: '/mock/jamb',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/exam': typeof AppExamRoute
  '/offline': typeof AppOfflineRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/review': typeof AppReviewRoute
  '/security': typeof AppSecurityRoute
  '/sovereignty': typeof AppSovereigntyRoute
  '/teachers': typeof AppTeachersRouteWithChildren
  '/tutor': typeof AppTutorRoute
  '/mock/jamb': typeof AppMockJambRoute
  '/mock/waec': typeof AppMockWaecRoute
  '/teachers/admin': typeof AppTeachersAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/exam': typeof AppExamRoute
  '/offline': typeof AppOfflineRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/review': typeof AppReviewRoute
  '/security': typeof AppSecurityRoute
  '/sovereignty': typeof AppSovereigntyRoute
  '/teachers': typeof AppTeachersRouteWithChildren
  '/tutor': typeof AppTutorRoute
  '/mock/jamb': typeof AppMockJambRoute
  '/mock/waec': typeof AppMockWaecRoute
  '/teachers/admin': typeof AppTeachersAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exam': typeof AppExamRoute
  '/_app/offline': typeof AppOfflineRoute
  '/_app/question-bank': typeof AppQuestionBankRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/sovereignty': typeof AppSovereigntyRoute
  '/_app/teachers': typeof AppTeachersRouteWithChildren
  '/_app/tutor': typeof AppTutorRoute
  '/_app/mock/jamb': typeof AppMockJambRoute
  '/_app/mock/waec': typeof AppMockWaecRoute
  '/_app/teachers/admin': typeof AppTeachersAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/dashboard'
    | '/exam'
    | '/offline'
    | '/question-bank'
    | '/review'
    | '/security'
    | '/sovereignty'
    | '/teachers'
    | '/tutor'
    | '/mock/jamb'
    | '/mock/waec'
    | '/teachers/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/dashboard'
    | '/exam'
    | '/offline'
    | '/question-bank'
    | '/review'
    | '/security'
    | '/sovereignty'
    | '/teachers'
    | '/tutor'
    | '/mock/jamb'
    | '/mock/waec'
    | '/teachers/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/exam'
    | '/_app/offline'
    | '/_app/question-bank'
    | '/_app/review'
    | '/_app/security'
    | '/_app/sovereignty'
    | '/_app/teachers'
    | '/_app/tutor'
    | '/_app/mock/jamb'
    | '/_app/mock/waec'
    | '/_app/teachers/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sovereignty': {
      id: '/_app/sovereignty'
      path: '/sovereignty'
      fullPath: '/sovereignty'
      preLoaderRoute: typeof AppSovereigntyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/question-bank': {
      id: '/_app/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AppQuestionBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offline': {
      id: '/_app/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof AppOfflineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exam': {
      id: '/_app/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AppExamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers/admin': {
      id: '/_app/teachers/admin'
      path: '/admin'
      fullPath: '/teachers/admin'
      preLoaderRoute: typeof AppTeachersAdminRouteImport
      parentRoute: typeof AppTeachersRoute
    }
    '/_app/mock/waec': {
      id: '/_app/mock/waec'
      path: '/mock/waec'
      fullPath: '/mock/waec'
      preLoaderRoute: typeof AppMockWaecRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock/jamb': {
      id: '/_app/mock/jamb'
      path: '/mock/jamb'
      fullPath: '/mock/jamb'
      preLoaderRoute: typeof AppMockJambRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTeachersRouteChildren {
  AppTeachersAdminRoute: typeof AppTeachersAdminRoute
}

const AppTeachersRouteChildren: AppTeachersRouteChildren = {
  AppTeachersAdminRoute: AppTeachersAdminRoute,
}

const AppTeachersRouteWithChildren = AppTeachersRoute._addFileChildren(
  AppTeachersRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExamRoute: typeof AppExamRoute
  AppOfflineRoute: typeof AppOfflineRoute
  AppQuestionBankRoute: typeof AppQuestionBankRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSovereigntyRoute: typeof AppSovereigntyRoute
  AppTeachersRoute: typeof AppTeachersRouteWithChildren
  AppTutorRoute: typeof AppTutorRoute
  AppMockJambRoute: typeof AppMockJambRoute
  AppMockWaecRoute: typeof AppMockWaecRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExamRoute: AppExamRoute,
  AppOfflineRoute: AppOfflineRoute,
  AppQuestionBankRoute: AppQuestionBankRoute,
  AppReviewRoute: AppReviewRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSovereigntyRoute: AppSovereigntyRoute,
  AppTeachersRoute: AppTeachersRouteWithChildren,
  AppTutorRoute: AppTutorRoute,
  AppMockJambRoute: AppMockJambRoute,
  AppMockWaecRoute: AppMockWaecRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
