/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppSovereigntyRouteImport } from './routes/_app/sovereignty'
import { Route as AppQuestionBankRouteImport } from './routes/_app/question-bank'
import { Route as AppExamRouteImport } from './routes/_app/exam'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMockWaecRouteImport } from './routes/_app/mock.waec'
import { Route as AppMockJambRouteImport } from './routes/_app/mock.jamb'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppSovereigntyRoute = AppSovereigntyRouteImport.update({
  id: '/sovereignty',
  path: '/sovereignty',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionBankRoute = AppQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AppRoute,
} as any)
const AppExamRoute = AppExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMockWaecRoute = AppMockWaecRouteImport.update({
  id: '/mock/waec',
  path: '/mock/waec',
  getParentRoute: () => AppRoute,
} as any)
const AppMockJambRoute = AppMockJambRouteImport.update({
  id: '/mock/jamb',
  path: '/mock/jamb',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/exam': typeof AppExamRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/sovereignty': typeof AppSovereigntyRoute
  '/tutor': typeof AppTutorRoute
  '/mock/jamb': typeof AppMockJambRoute
  '/mock/waec': typeof AppMockWaecRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/exam': typeof AppExamRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/sovereignty': typeof AppSovereigntyRoute
  '/tutor': typeof AppTutorRoute
  '/mock/jamb': typeof AppMockJambRoute
  '/mock/waec': typeof AppMockWaecRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exam': typeof AppExamRoute
  '/_app/question-bank': typeof AppQuestionBankRoute
  '/_app/sovereignty': typeof AppSovereigntyRoute
  '/_app/tutor': typeof AppTutorRoute
  '/_app/mock/jamb': typeof AppMockJambRoute
  '/_app/mock/waec': typeof AppMockWaecRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/exam'
    | '/question-bank'
    | '/sovereignty'
    | '/tutor'
    | '/mock/jamb'
    | '/mock/waec'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/exam'
    | '/question-bank'
    | '/sovereignty'
    | '/tutor'
    | '/mock/jamb'
    | '/mock/waec'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/exam'
    | '/_app/question-bank'
    | '/_app/sovereignty'
    | '/_app/tutor'
    | '/_app/mock/jamb'
    | '/_app/mock/waec'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sovereignty': {
      id: '/_app/sovereignty'
      path: '/sovereignty'
      fullPath: '/sovereignty'
      preLoaderRoute: typeof AppSovereigntyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/question-bank': {
      id: '/_app/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AppQuestionBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exam': {
      id: '/_app/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AppExamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock/waec': {
      id: '/_app/mock/waec'
      path: '/mock/waec'
      fullPath: '/mock/waec'
      preLoaderRoute: typeof AppMockWaecRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock/jamb': {
      id: '/_app/mock/jamb'
      path: '/mock/jamb'
      fullPath: '/mock/jamb'
      preLoaderRoute: typeof AppMockJambRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExamRoute: typeof AppExamRoute
  AppQuestionBankRoute: typeof AppQuestionBankRoute
  AppSovereigntyRoute: typeof AppSovereigntyRoute
  AppTutorRoute: typeof AppTutorRoute
  AppMockJambRoute: typeof AppMockJambRoute
  AppMockWaecRoute: typeof AppMockWaecRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExamRoute: AppExamRoute,
  AppQuestionBankRoute: AppQuestionBankRoute,
  AppSovereigntyRoute: AppSovereigntyRoute,
  AppTutorRoute: AppTutorRoute,
  AppMockJambRoute: AppMockJambRoute,
  AppMockWaecRoute: AppMockWaecRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
